In [33]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
df = pd.read_csv('Iris.csv')

In [3]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [7]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [8]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [9]:
df['Species'] = df['Species'].astype('category')

In [14]:
columns = df.columns
columns
df.dtypes

Id                  int64
SepalLengthCm     float64
SepalWidthCm      float64
PetalLengthCm     float64
PetalWidthCm      float64
Species          category
dtype: object

In [16]:
for i in columns:
    if i != 'Species':
        df[i] = df[i].fillna(df[i].mean())

In [17]:
df['Species'] = df['Species'].fillna(df['Species'].mode()[0])

In [19]:
df.shape

(150, 6)

In [22]:
df['SepalLengthCm'] = (df['SepalLengthCm']-df['SepalLengthCm'].min())/(df['SepalLengthCm'].max()-df['SepalLengthCm'].min())

In [23]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,0.222222,3.5,1.4,0.2,Iris-setosa
1,2,0.166667,3.0,1.4,0.2,Iris-setosa
2,3,0.111111,3.2,1.3,0.2,Iris-setosa
3,4,0.083333,3.1,1.5,0.2,Iris-setosa
4,5,0.194444,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,0.666667,3.0,5.2,2.3,Iris-virginica
146,147,0.555556,2.5,5.0,1.9,Iris-virginica
147,148,0.611111,3.0,5.2,2.0,Iris-virginica
148,149,0.527778,3.4,5.4,2.3,Iris-virginica
149,150,0.444444,3.0,5.1,1.8,Iris-virginica

In [24]:
print(df['SepalLengthCm'].min())
print(df['SepalLengthCm'].max())

0.0
1.0

In [25]:
df['Species'] = df['Species'].cat.codes

In [26]:
df['Species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int8

In [27]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species             int8
dtype: object

In [28]:
df.drop(columns='Id', inplace=True)

In [29]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0         0.222222           3.5            1.4           0.2        0
1         0.166667           3.0            1.4           0.2        0
2         0.111111           3.2            1.3           0.2        0
3         0.083333           3.1            1.5           0.2        0
4         0.194444           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145       0.666667           3.0            5.2           2.3        2
146       0.555556           2.5            5.0           1.9        2
147       0.611111           3.0            5.2           2.0        2
148       0.527778           3.4            5.4           2.3        2
149       0.444444           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [30]:
df['SepalWidthCm'] = np.log(df['SepalWidthCm'])

In [31]:
df['SepalWidthCm']

0      1.252763
1      1.098612
2      1.163151
3      1.131402
4      1.280934
         ...
145    1.098612
146    0.916291
147    1.098612
148    1.223775
149    1.098612
Name: SepalWidthCm, Length: 150, dtype: float64

In [37]:
scaler1 = StandardScaler()
df['PetalWidthCm'] = scaler1.fit_transform(df[['PetalWidthCm']])

In [38]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0         0.222222      1.252763            1.4     -1.312977        0
1         0.166667      1.098612            1.4     -1.312977        0
2         0.111111      1.163151            1.3     -1.312977        0
3         0.083333      1.131402            1.5     -1.312977        0
4         0.194444      1.280934            1.4     -1.312977        0
..             ...           ...            ...           ...      ...
145       0.666667      1.098612            5.2      1.447956        2
146       0.555556      0.916291            5.0      0.922064        2
147       0.611111      1.098612            5.2      1.053537        2
148       0.527778      1.223775            5.4      1.447956        2
149       0.444444      1.098612            5.1      0.790591        2

[150 rows x 5 columns]

In [39]:
df['PetalWidthCm'].mean()

np.float64(-2.842170943040401e-16)

In [40]:
round(df['PetalWidthCm'].mean(), 5)

np.float64(-0.0)